version: "3"

services:
  jwt_postgres:
    image: postgres:17-alpine
    container_name: jwt_postgres
    restart: "no"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "jwt"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - jwt_postgres:/var/lib/postgresql/data
volumes:
  jwt_postgres: